# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-org
# - jemoji-plus

# Gem Settings
author: Khinshan Khan # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Khinshan Khan # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/khinshankhan
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# Pagination
paginate: 5
paginate_path: blog/page/:num

# Site settings
url: 'https://khinshankhan.com'
baseurl: ''
title: 'Khinshan Khan'
description: "Hello! This is my personal blog, where I share interesting news, books I'm reading, shows I'm watching, prominent projects, what I'm learning, and some musings. You can also find a plethora of information on myself, or at least sources to them.
</br></br>
 クリック コード サイクル！"
permalink: /:year/:month/:day/:title
logo: "/assets/imgs/works/k_logo.jpeg"

disqus: "kkhan01"

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about
- title: Blog
  url: /blog/
- title: Projects
  url: /projects
- title: Search
  url: /search
- title: Resume
  url: https://kkhan01.github.io/resume/resume.pdf

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      ## Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Favicons are also used in the manifest file. Syntax is 'size: path'
favicons:
  16: '/assets/imgs/works/k_logo.jpeg'
  32: '/assets/imgs/works/k_logo.jpeg'
  96: '/assets/imgs/works/k_logo.jpeg'
  120: '/assets/imgs/works/k_logo.jpeg'
  144: '/assets/imgs/works/k_logo.jpeg'
  180: '/assets/imgs/works/k_logo.jpeg'
  512: '/assets/imgs/works/k_logo.jpeg'
  1024: '/assets/imgs/works/k_logo.jpeg'

social_links:
  GitHub: https://github.com/khinshankhan
  Linkedin: https://linkedin.com/in/khinshankhan
  Discord: https://discordapp.com/users/356260437567995914/
  RSS: /feed.xml


########################################################
# jemoji setting
#
# See: https://github.com/jekyll/jemoji
#
# command:
# gem install gemoji
# bundle exec gemoji extract assets/images/emoji
#
########################################################
emoji:
  # src: "/static/images/icons/emoji"
  src: "https://github.githubassets.com/images/icons/"
